Resources:
  DynamicThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          NODE_ATTRIBUTE: "@_id"
          NODE_VALUE: "view-count"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2020
        Sourcemap: inline
        Loader:
          - .svg=file
        EntryPoints:
          - src/app.ts
